### ISSUE TITLE
Run->Motor->Go

### ISSUE THREAD

**Issue by f4deb** [svanacker/cen-info-kinect#20]
When I push the go button, the speed of left motor set the speed of right motor.

1-> set left value different that right value
2-> select Go button
3-> in the console view, for example,these commands are pushed : 

mw0505
amwmw1414
amwmw1414
amwmw2222
amwmw0909
amwmw3535
amwmw1818
amwmwE5E5
amwmw2222
amwmw0303
amwmc
amc

**Comment by svanacker** [comment]
Just fixed,
